export default function ReasoningTrace() {
  const traces = [
    "Relational workload identified",
    "Transactional consistency required",
    "High write throughput detected",
    "Analytical query patterns extracted",
    "Index optimization strategy generated",
    "Recommendation confidence: 91%",
  ];

  return (
    <div className="rounded-[32px] border border-zinc-900 bg-zinc-950/70 overflow-hidden">
      <div className="border-b border-zinc-900 px-6 py-5 flex items-center justify-between">
        <div>
          <p className="text-sm font-medium">Reasoning Trace</p>
          <p className="mt-1 text-xs text-zinc-500">
            Internal decision chain generated by the runtime
          </p>
        </div>

        <div className="text-xs text-zinc-600">
          trace_id: sf_rt_2041
        </div>
      </div>

      <div className="p-6 space-y-4">
        {traces.map((trace, index) => (
          <div
            key={trace}
            className="flex items-center justify-between rounded-2xl border border-zinc-900 bg-black px-5 py-4"
          >
            <div className="flex items-center gap-4">
              <div className="h-2.5 w-2.5 rounded-full bg-emerald-500" />

              <p className="text-sm text-zinc-300">{trace}</p>
            </div>

            <div className="text-xs text-zinc-600">
              step_{index + 1}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}