function ArchitectureGraph() {
  return (
    <div className="rounded-[32px] border border-zinc-900 bg-zinc-950/70 overflow-hidden">
      <div className="border-b border-zinc-900 px-6 py-5 flex items-center justify-between">
        <div>
          <p className="text-sm font-medium">
            Generated Architecture Graph
          </p>
          <p className="mt-1 text-xs text-zinc-500">
            Runtime topology synthesized from workload constraints
          </p>
        </div>

        <div className="rounded-full border border-zinc-800 px-3 py-1 text-xs text-zinc-500">
          Graph Layer
        </div>
      </div>

      <div className="relative p-10 min-h-[420px] bg-black overflow-hidden">
        <div className="absolute inset-0 opacity-[0.03]">
          <div
            className="absolute inset-0"
            style={{
              backgroundImage:
                "linear-gradient(to right, white 1px, transparent 1px), linear-gradient(to bottom, white 1px, transparent 1px)",
              backgroundSize: "32px 32px",
            }}
          />
        </div>

        <div className="relative flex flex-col items-center gap-12">
          <div className="rounded-3xl border border-zinc-800 bg-zinc-950 px-8 py-5 text-center shadow-2xl shadow-black/30">
            <p className="text-xs uppercase tracking-widest text-zinc-600">
              Client Layer
            </p>
            <h3 className="mt-3 text-lg font-semibold">Next.js Frontend</h3>
          </div>

          <div className="h-12 w-px bg-zinc-800" />

          <div className="grid grid-cols-2 gap-12">
            <div className="rounded-3xl border border-zinc-800 bg-zinc-950 px-8 py-5 text-center">
              <p className="text-xs uppercase tracking-widest text-zinc-600">
                Backend Runtime
              </p>
              <h3 className="mt-3 text-lg font-semibold">Node.js API</h3>
            </div>

            <div className="rounded-3xl border border-emerald-500/20 bg-emerald-500/5 px-8 py-5 text-center">
              <p className="text-xs uppercase tracking-widest text-emerald-500/60">
                AI Runtime
              </p>
              <h3 className="mt-3 text-lg font-semibold">FastAPI + Agno</h3>
            </div>
          </div>

          <div className="grid grid-cols-3 gap-10">
            {[
              "PostgreSQL",
              "Redis Cache",
              "pgvector",
            ].map((service) => (
              <div
                key={service}
                className="rounded-3xl border border-zinc-900 bg-zinc-950 px-6 py-5 text-center"
              >
                <p className="text-xs uppercase tracking-widest text-zinc-600">
                  Infrastructure
                </p>
                <h3 className="mt-3 text-base font-medium">{service}</h3>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

function AnalysisMetadata() {
  const metadata = [
    {
      label: "Estimated Throughput",
      value: "12k writes/min",
    },
    {
      label: "Consistency Model",
      value: "Strong Consistency",
    },
    {
      label: "Read/Write Ratio",
      value: "65 / 35",
    },
    {
      label: "Index Strategy",
      value: "Composite + GIN",
    },
    {
      label: "Latency Target",
      value: "< 120ms",
    },
    {
      label: "Scalability Pattern",
      value: "Horizontal API Scaling",
    },
  ];

  return (
    <div className="rounded-[32px] border border-zinc-900 bg-zinc-950/70 overflow-hidden">
      <div className="border-b border-zinc-900 px-6 py-5">
        <p className="text-sm font-medium">Analysis Metadata</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4 p-6">
        {metadata.map((item) => (
          <div
            key={item.label}
            className="rounded-3xl border border-zinc-900 bg-black p-5"
          >
            <p className="text-xs uppercase tracking-widest text-zinc-600">
              {item.label}
            </p>

            <h3 className="mt-4 text-lg font-semibold tracking-tight">
              {item.value}
            </h3>
          </div>
        ))}
      </div>
    </div>
  );
}

function ReasoningTrace() {
  const traces = [
    "Relational workload identified",
    "Transactional consistency required",
    "High write throughput detected",
    "Analytical query patterns extracted",
    "Index optimization strategy generated",
    "Recommendation confidence: 91%",
  ];

  return (
    <div className="rounded-[32px] border border-zinc-900 bg-zinc-950/70 overflow-hidden">
      <div className="border-b border-zinc-900 px-6 py-5 flex items-center justify-between">
        <div>
          <p className="text-sm font-medium">Reasoning Trace</p>
          <p className="mt-1 text-xs text-zinc-500">
            Internal decision chain generated by the runtime
          </p>
        </div>

        <div className="text-xs text-zinc-600">
          trace_id: sf_rt_2041
        </div>
      </div>

      <div className="p-6 space-y-4">
        {traces.map((trace, index) => (
          <div
            key={trace}
            className="flex items-center justify-between rounded-2xl border border-zinc-900 bg-black px-5 py-4"
          >
            <div className="flex items-center gap-4">
              <div className="h-2.5 w-2.5 rounded-full bg-emerald-500" />

              <p className="text-sm text-zinc-300">{trace}</p>
            </div>

            <div className="text-xs text-zinc-600">
              step_{index + 1}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

function HistoryPage() {
  const sessions = [
    "Realtime Ecommerce Infrastructure",
    "Distributed Analytics Platform",
    "Financial Transaction System",
    "Event-driven Notification Pipeline",
  ];

  return (
    <div className="min-h-screen bg-[#050505] text-zinc-100 px-6 py-10">
      <div className="max-w-6xl mx-auto">
        <div>
          <h1 className="text-5xl font-semibold tracking-tight">
            Architecture Sessions
          </h1>

          <p className="mt-4 text-zinc-500 max-w-2xl leading-8">
            Persisted infrastructure reasoning sessions, runtime outputs and database architecture analyses.
          </p>
        </div>

        <div className="mt-12 grid gap-5">
          {sessions.map((session, index) => (
            <div
              key={session}
              className="rounded-[28px] border border-zinc-900 bg-zinc-950/70 p-6 flex items-center justify-between"
            >
              <div>
                <p className="text-xl font-medium tracking-tight">
                  {session}
                </p>

                <p className="mt-2 text-sm text-zinc-500">
                  Generated runtime topology, schema reasoning and infrastructure recommendations.
                </p>
              </div>

              <div className="text-right">
                <p className="text-xs text-zinc-600">
                  session_{index + 1}
                </p>

                <button className="mt-3 rounded-2xl border border-zinc-800 bg-black px-4 py-2 text-sm text-zinc-400 hover:text-zinc-100 transition">
                  Open Workspace
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export { ArchitectureGraph, AnalysisMetadata, ReasoningTrace, HistoryPage };

export default function ConstraintEngineFinalUI() {
  const recommendations = [
    {
      category: "Primary Database",
      value: "PostgreSQL",
      reason:
        "Strong transactional consistency, mature relational modeling and scalable indexing capabilities.",
    },
    {
      category: "Caching Layer",
      value: "Redis",
      reason:
        "Low latency cache layer for inventory synchronization and session acceleration.",
    },
    {
      category: "Vector Memory",
      value: "pgvector",
      reason:
        "Semantic retrieval and architecture memory integration within PostgreSQL.",
    },
  ];

  return (
    <div className="min-h-screen bg-[#050505] text-zinc-100">
      {/* Background Grid */}
      <div className="fixed inset-0 opacity-[0.04] pointer-events-none">
        <div
          className="absolute inset-0"
          style={{
            backgroundImage:
              "linear-gradient(to right, white 1px, transparent 1px), linear-gradient(to bottom, white 1px, transparent 1px)",
            backgroundSize: "40px 40px",
          }}
        />
      </div>

      {/* Navbar */}
      <header className="sticky top-0 z-50 border-b border-zinc-900 backdrop-blur-xl bg-black/40">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <div className="h-10 w-10 rounded-2xl border border-zinc-800 bg-zinc-950 flex items-center justify-center text-sm font-semibold">
              CE
            </div>

            <div>
              <h1 className="text-lg font-semibold tracking-tight">
                ConstraintEngine
              </h1>
              <p className="text-xs text-zinc-500">
                Infrastructure reasoning runtime
              </p>
            </div>
          </div>

          <div className="hidden md:flex items-center gap-8 text-sm text-zinc-400">
            <button className="hover:text-zinc-100 transition">
              Architecture
            </button>
            <button className="hover:text-zinc-100 transition">
              Runtime
            </button>
            <button className="hover:text-zinc-100 transition">
              Docs
            </button>
          </div>

          <button className="rounded-2xl border border-zinc-800 bg-zinc-950 px-4 py-2 text-sm hover:bg-zinc-900 transition">
            Sign In
          </button>
        </div>
      </header>

      {/* Hero + Workspace */}
      <section className="relative max-w-7xl mx-auto px-6 pt-16 pb-10">
        <div className="max-w-4xl">
          <div className="inline-flex items-center gap-2 rounded-full border border-zinc-800 bg-zinc-950 px-4 py-2 text-xs text-zinc-400">
            <div className="h-2 w-2 rounded-full bg-emerald-500" />
            AI Agent Runtime Operational
          </div>

          <h1 className="mt-8 text-5xl md:text-7xl font-semibold tracking-tight leading-none">
            Constraint-aware
            <br />
            infrastructure reasoning.
          </h1>

          <p className="mt-8 max-w-2xl text-lg leading-8 text-zinc-400">
            Analyze backend workloads, schema design, database selection,
            indexing strategies and infrastructure tradeoffs through an AI-native
            systems reasoning engine.
          </p>
        </div>

        {/* Workspace */}
        <div className="mt-16 grid grid-cols-12 gap-6">
          {/* Left Input Side */}
          <section className="col-span-12 lg:col-span-5 space-y-6">
            <div className="rounded-[32px] border border-zinc-900 bg-zinc-950/70 backdrop-blur overflow-hidden">
              <div className="border-b border-zinc-900 px-6 py-5 flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium">
                    Workload Definition
                  </p>
                  <p className="mt-1 text-xs text-zinc-500">
                    Describe your architecture and system constraints
                  </p>
                </div>

                <div className="rounded-full border border-zinc-800 px-3 py-1 text-xs text-zinc-500">
                  Input Layer
                </div>
              </div>

              <div className="p-6">
                <textarea
                  placeholder="Building ecommerce system with realtime inventory, analytical queries and scalable transactional workload..."
                  className="w-full min-h-[260px] resize-none rounded-3xl border border-zinc-900 bg-black px-5 py-5 text-sm leading-8 outline-none placeholder:text-zinc-600"
                />

                <div className="mt-6 flex flex-wrap gap-2">
                  {[
                    "High write throughput",
                    "Relational schema",
                    "ACID consistency",
                    "Realtime inventory",
                    "Analytics workload",
                    "Scalable API layer",
                  ].map((item) => (
                    <div
                      key={item}
                      className="rounded-full border border-zinc-800 bg-black px-3 py-1.5 text-xs text-zinc-400"
                    >
                      {item}
                    </div>
                  ))}
                </div>

                <div className="mt-8 flex items-center gap-4">
                  <button className="flex-1 rounded-2xl bg-zinc-100 py-3.5 text-sm font-medium text-black hover:bg-zinc-300 transition">
                    Run Analysis
                  </button>

                  <button className="rounded-2xl border border-zinc-800 bg-black px-5 py-3.5 text-sm text-zinc-400 hover:text-zinc-100 transition">
                    Examples
                  </button>
                </div>
              </div>
            </div>
          </section>

          {/* Right Recommendation Side */}
          <section className="col-span-12 lg:col-span-7 space-y-6">
            {/* Recommendation Output */}
            <div className="rounded-[32px] border border-zinc-900 bg-zinc-950/70 overflow-hidden">
              <div className="border-b border-zinc-900 px-6 py-5 flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium">
                    Infrastructure Recommendation
                  </p>
                  <p className="mt-1 text-xs text-zinc-500">
                    Generated architecture synthesis output
                  </p>
                </div>

                <div className="rounded-full border border-emerald-500/20 bg-emerald-500/10 px-3 py-1 text-xs text-emerald-400">
                  Runtime Active
                </div>
              </div>

              <div className="p-6 grid grid-cols-1 md:grid-cols-3 gap-5">
                {recommendations.map((item) => (
                  <div
                    key={item.category}
                    className="rounded-3xl border border-zinc-900 bg-black p-5"
                  >
                    <p className="text-xs uppercase tracking-wider text-zinc-600">
                      {item.category}
                    </p>

                    <h2 className="mt-5 text-3xl font-semibold tracking-tight">
                      {item.value}
                    </h2>

                    <p className="mt-5 text-sm leading-7 text-zinc-500">
                      {item.reason}
                    </p>
                  </div>
                ))}
              </div>
            </div>

            {/* Reasoning Output */}
            <div className="rounded-[32px] border border-zinc-900 bg-zinc-950/70 overflow-hidden">
              <div className="border-b border-zinc-900 px-6 py-5 flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium">
                    Constraint Reasoning
                  </p>
                  <p className="mt-1 text-xs text-zinc-500">
                    Internal infrastructure analysis generated by the reasoning engine
                  </p>
                </div>

                <div className="text-xs text-zinc-600">
                  latency 1.2s
                </div>
              </div>

              <div className="p-6">
                <div className="rounded-3xl border border-zinc-900 bg-black p-6">
                  <p className="text-sm leading-8 text-zinc-300">
                    The workload indicates a transactional system requiring
                    strong relational consistency alongside analytical querying
                    and inventory synchronization. PostgreSQL is recommended as
                    the primary operational database because it provides mature
                    ACID guarantees, indexing flexibility and scalable
                    relational modeling. Redis should be introduced as a
                    supplementary caching layer to accelerate realtime access
                    paths and reduce repeated query pressure.
                  </p>
                </div>
              </div>
            </div>
          </section>
        </div>
      </section>
    </div>
  );
}

export function ConstraintEngineLanding() {
  const capabilities = [
    "Constraint Parsing",
    "Schema Synthesis",
    "Topology Generation",
    "Index Optimization",
    "RAG-based Retrieval",
    "Vector Memory Reasoning",
  ];

  const workloads = [
    {
      title: "Realtime Ecommerce Platform",
      description:
        "Inventory synchronization, transactional consistency, analytics workloads, and recommendation systems.",
      tags: ["High throughput", "ACID", "Realtime sync"],
    },
    {
      title: "Multi-Tenant SaaS Infrastructure",
      description:
        "Tenant isolation, audit logging, billing systems, horizontal scaling, and API orchestration.",
      tags: ["Multi-tenant", "Scalable APIs", "Security"],
    },
    {
      title: "AI-native Knowledge Platform",
      description:
        "Semantic retrieval, contextual memory, vector search, and hybrid database architecture.",
      tags: ["Embeddings", "RAG", "Hybrid storage"],
    },
  ];

  return (
    <div className="min-h-screen bg-[#050505] text-zinc-100 overflow-hidden">
      {/* Background */}
      <div className="fixed inset-0 opacity-[0.035] pointer-events-none">
        <div className="h-full w-full bg-[linear-gradient(to_right,#ffffff10_1px,transparent_1px),linear-gradient(to_bottom,#ffffff10_1px,transparent_1px)] bg-[size:52px_52px]" />
      </div>

      {/* Navbar */}
      <header className="relative z-50 border-b border-zinc-900 bg-black/70 backdrop-blur-xl">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <div>
            <h1 className="text-xl font-semibold tracking-tight">
              ConstraintEngine
            </h1>
            <p className="text-xs text-zinc-500 mt-0.5">
              AI-native backend architecture reasoning platform
            </p>
          </div>

          <div className="hidden md:flex items-center gap-8 text-sm text-zinc-500">
            <button className="hover:text-zinc-200 transition">
              Runtime
            </button>
            <button className="hover:text-zinc-200 transition">
              Retrieval
            </button>
            <button className="hover:text-zinc-200 transition">
              Topology
            </button>
            <button className="hover:text-zinc-200 transition">
              Documentation
            </button>
          </div>

          <button className="rounded-2xl border border-zinc-800 bg-zinc-950 px-4 py-2 text-sm hover:bg-zinc-900 transition">
            Open Workspace
          </button>
        </div>
      </header>

      {/* Hero */}
      <section className="relative">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_top,rgba(16,185,129,0.14),transparent_45%)]" />

        <div className="relative max-w-7xl mx-auto px-6 pt-24 pb-20 lg:pt-32 lg:pb-28">
          <div className="max-w-5xl">
            <div className="inline-flex items-center gap-2 rounded-full border border-emerald-500/20 bg-emerald-500/10 px-4 py-1.5 text-xs text-emerald-400">
              Constraint-aware infrastructure synthesis engine
            </div>

            <h2 className="mt-8 text-5xl lg:text-7xl font-semibold tracking-tight leading-[1.02] max-w-5xl">
              Design scalable backend architectures through AI-native reasoning.
            </h2>

            <p className="mt-8 max-w-3xl text-lg leading-8 text-zinc-400">
              Analyze workloads, evaluate infrastructure constraints, generate database topologies, and synthesize backend architectures through orchestration-aware reasoning pipelines.
            </p>

            <div className="mt-10 flex flex-wrap gap-4">
              <button className="rounded-2xl bg-zinc-100 px-6 py-3 text-sm font-medium text-black hover:bg-zinc-300 transition">
                Launch Infrastructure Workspace
              </button>

              <button className="rounded-2xl border border-zinc-800 bg-zinc-950 px-6 py-3 text-sm text-zinc-300 hover:bg-zinc-900 transition">
                View Runtime Pipeline
              </button>
            </div>
          </div>

          {/* Hero Runtime Preview */}
          <div className="mt-20 rounded-[32px] border border-zinc-900 bg-[#090909] overflow-hidden shadow-[0_0_0_1px_rgba(255,255,255,0.02)]">
            <div className="flex items-center justify-between border-b border-zinc-900 px-6 py-5">
              <div>
                <p className="text-sm font-medium text-zinc-200">
                  Runtime Pipeline Preview
                </p>
                <p className="mt-1 text-xs text-zinc-500">
                  Internal orchestration flow for infrastructure synthesis
                </p>
              </div>

              <div className="rounded-full border border-emerald-500/20 bg-emerald-500/10 px-3 py-1 text-xs text-emerald-400">
                Runtime Active
              </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-5 gap-px bg-zinc-900">
              {[
                "Constraint Parsing",
                "Knowledge Retrieval",
                "Agent Reasoning",
                "Topology Synthesis",
                "Optimization Layer",
              ].map((step) => (
                <div
                  key={step}
                  className="bg-black px-6 py-8"
                >
                  <div className="h-2.5 w-2.5 rounded-full bg-emerald-500" />

                  <h3 className="mt-6 text-sm font-medium text-zinc-200 leading-6">
                    {step}
                  </h3>

                  <p className="mt-4 text-sm leading-7 text-zinc-500">
                    Runtime stage orchestrated through AI-native workflow execution.
                  </p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Capability Layer */}
      <section className="border-t border-zinc-900">
        <div className="max-w-7xl mx-auto px-6 py-20">
          <div className="flex items-end justify-between gap-8 flex-wrap">
            <div>
              <p className="text-sm text-emerald-400">
                Core System Capabilities
              </p>

              <h3 className="mt-4 text-3xl lg:text-5xl font-semibold tracking-tight max-w-3xl leading-tight">
                Designed for backend architecture analysis and infrastructure reasoning.
              </h3>
            </div>

            <p className="max-w-xl text-sm leading-7 text-zinc-500">
              ConstraintEngine combines retrieval pipelines, agent orchestration, database analysis, and workload synthesis into a unified infrastructure reasoning environment.
            </p>
          </div>

          <div className="mt-16 grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-5">
            {capabilities.map((capability, index) => (
              <div
                key={capability}
                className="rounded-3xl border border-zinc-900 bg-[#090909] p-6 hover:border-emerald-500/20 transition"
              >
                <div className="flex items-center justify-between">
                  <div className="h-10 w-10 rounded-2xl border border-zinc-800 bg-black flex items-center justify-center text-sm text-zinc-400">
                    0{index + 1}
                  </div>

                  <div className="rounded-full border border-zinc-800 px-3 py-1 text-[11px] uppercase tracking-wide text-zinc-500">
                    Active
                  </div>
                </div>

                <h4 className="mt-8 text-2xl font-semibold tracking-tight leading-tight">
                  {capability}
                </h4>

                <p className="mt-5 text-sm leading-7 text-zinc-500">
                  Infrastructure-aware reasoning workflow designed for scalable backend systems and modern distributed architectures.
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Workload Examples */}
      <section className="border-t border-zinc-900">
        <div className="max-w-7xl mx-auto px-6 py-20">
          <div className="max-w-3xl">
            <p className="text-sm text-emerald-400">
              Interactive Workload Templates
            </p>

            <h3 className="mt-4 text-3xl lg:text-5xl font-semibold tracking-tight leading-tight">
              Start from realistic backend architecture scenarios.
            </h3>
          </div>

          <div className="mt-14 grid grid-cols-1 xl:grid-cols-3 gap-6">
            {workloads.map((workload) => (
              <button
                key={workload.title}
                className="group rounded-[32px] border border-zinc-900 bg-[#090909] p-7 text-left hover:border-emerald-500/20 hover:bg-[#0c0c0c] transition"
              >
                <div className="flex items-center justify-between">
                  <div className="rounded-full border border-zinc-800 bg-black px-3 py-1 text-[11px] uppercase tracking-wide text-zinc-500">
                    Workload
                  </div>

                  <div className="text-zinc-700 group-hover:text-emerald-400 transition">
                    →
                  </div>
                </div>

                <h4 className="mt-8 text-3xl font-semibold tracking-tight leading-tight">
                  {workload.title}
                </h4>

                <p className="mt-6 text-sm leading-8 text-zinc-500">
                  {workload.description}
                </p>

                <div className="mt-8 flex flex-wrap gap-2">
                  {workload.tags.map((tag) => (
                    <div
                      key={tag}
                      className="rounded-full border border-zinc-800 bg-black px-3 py-1 text-xs text-zinc-300"
                    >
                      {tag}
                    </div>
                  ))}
                </div>
              </button>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}

